apiVersion: v1
kind: Secret
metadata:
    name: sample-secret
    namespace: default
type: Opaque
stringData:
    example: ENC[AES256_GCM,data:LJUza3dCLw2HaA==,iv:7udNg+NIU7XFoXBhRHHNFQhcxx9cTmcnKeRUuK0Q0Qs=,tag:NMFBACYvoK3vuzOTbkf0lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUU51dHJEOWt3SkRLUEUw
            MEVnUEoyNlZMSW1COUVXd3gwVlpESjE2bms0CnRWelJHSXJGQzJ0aWx4YW1nN2Rv
            NkdTbkpmM0lYQXNUdmZJaXpnOUxpdWMKLS0tIEw0TEZwWWpSS2d6R2dRREFlODhF
            d0lQQ3B1N0VSQ2JocllkYWpFejJPUncK+Fe+lhS4BlSQxBdLWa9pILUWrRcr8MjM
            Bfh9jjXXgbMFUTXIsXAx1b/Z59p6yt1mQCcCRgPmu4Ln621tx++0CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17nrx95gprwykg0g0t4xexgm8792vy6tdp0k6y08avtz0uqyhefdsfmf9we
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-09T06:05:43Z"
    mac: ENC[AES256_GCM,data:Ts9sZ1BDGdJuSZX1bFOLQDDh2wv+OLoRto1ax5QTmDNSx5sLTLS7HgHMt+iH1j6a9rmDMs+81USrM/aChQABPpwGFcInD74yHfkREJa3J2b0C6JkemB71kVk+LIRIlGv9iqyJhOLgCY+ZEKH+plc0s9RRY+xDvgNo1LAyKHUQKQ=,iv:AcUtZcD95JODWdukYiajVSd8ADyAwCCIz8qDZgIANbo=,tag:RlGXU+glYWXh0KYn96/7Pg==,type:str]
    version: 3.13.0
